### PR TITLE
add message to update the baud rate of configured serial port

### PR DESCRIPTION
**Pull request by soundanalogous**
Proposal to add a message to update the baud rate of a configured serial port. This is useful for applications where the user needs to change the baud rate to something more manageable. A specific example is the need to drop the baud rate for a device that defaults at 115200 ( which is not reliable for SoftwareSerial in Firmata) down to a lower rate such as 9600.

### CODE REVIEW

**Comment by soundanalogous** [comment]
I really need to separate feature protocol version from core protocol version, that would enable making changes like this without needing to bump the core protocol version. For example if Serial had it's own protocol version, this would bump it from 1.0.0 to 1.1.0 instead of having to bump the core protocol version to 2.6.0. More leverage for something like this: https://github.com/firmata/protocol/issues/41.

**Comment by soundanalogous** [comment]
doh! `0x80` cannot be used here. One option, since `0x00` is not currently used it to treat `0x00` to signal an extended command set. I should have separated portId and sub-command from the beginning. 

```
0  START_SYSEX        (0xF0)
1  SERIAL_MESSAGE     (0x60)
2  SERIAL_EXTEND      (0x00) // OR with port to switch to (0x09 = SERIAL_EXTEND | SW_SERIAL1)
3  SERIAL_UPDATE_BAUD (0x01) // up to 127 extended commands
4  baud               (bits 0 - 6)
5  baud               (bits 7 - 13)
6  baud               (bits 14 - 20) // need to send 3 bytes for baud even if value is < 14 bits
7  END_SYSEX          (0xF7)
```

**Comment by soundanalogous** [comment]
I really need to establish a Firmata protocol review committee. It's too easy to make stupid mistakes when no one else is reviewing my work.

**Comment by rwaldron** [comment]
>  I should have separated portId and sub-command from the beginning.

I don't think it's too late to make this change. 

> I really need to establish a Firmata protocol review committee. It's too easy to make stupid mistakes when no one else is reviewing my work.

I actually reviewed this several times for you and missed it as well—the more (informed and experienced) reviewers, the better.

**Comment by rwaldron** [comment]
It might be worth it to write a "validator" that validates new additions against existing protocol forms.

**Comment by soundanalogous** [comment]
> I don't think it's too late to make this change.

All of the existing commands would need to be deprecated. Serial is already in use in node-firmata and perl-firmata.

**Comment by soundanalogous** [comment]
> It might be worth it to write a "validator" that validates new additions against existing protocol forms.

That's a good idea. Part of the issue however is I'm still exploring patterns. I want to avoid the crazy overpacked I2C_REQUEST pattern (byte 3), but I don't want things to be too sparse if they don't have to be so I thought this `command OR'd with id` pattern was going to be a good model going forward but totally overlooked the limitation in how many commands that could support.

**Comment by soundanalogous** [comment]
In hindsight, I also could have flipped it and OR's ID with COMMAND instead of COMMAND with ID and had 8 ids and 16 commands.

**Comment by soundanalogous** [comment]
The ideal scalable way to define a protocol that requires a range of IDs as well as a range of Commands would be:

```
0  START_SYSEX        (0xF0)
1  MESSAGE_BYTE       (0x60)     // identifies feature or device
2  COMMAND_BYTE       (0 - 127)  // identifies a function of the feature or device
3  ID_BYTE            (0 - 127)  // identifies a specific device or pin
... additional bytes
N  END_SYSEX          (0xF7)
```

OR even 2 bytes for the message since the message bytes are (slowly) running out:

```
0  START_SYSEX        (0xF0)
1  MESSAGE_BYTE_LSB
2  MESSAGE_BYTE_MSB
2  COMMAND_BYTE       (0 - 127)
3  ID_BYTE            (0 - 127)
... additional bytes
N  END_SYSEX          (0xF7)
```

And then sometimes additional bits can be packed with the COMMAND if they are related to the function it represents (and would not prevent scalability).

**Comment by rwaldron** [comment]
> All of the existing Serial commands would need to be deprecated. Serial is already in use in node-firmata and perl-firmata although probably not by too many users at this point in time.

I didn't realize perl-firmata had already implemented, but I was willing to try to convince you that we could do a breaking release of node firmata to buy you the fix window ;)

**Comment by soundanalogous** [comment]
I don't even think a major change in the protocol would need to change the node-firmata API at all, however there would be two versions of StandardFirmataPlus floating around (v2.5.0 and v2.5.1) that have the old Serial API and I think v 2.5.0 is included with the Arduino IDE download.

**Comment by rwaldron** [comment]
I see, then consider that settled.

**Comment by soundanalogous** [comment]
Also, nothing is broken in the existing implementation. I just unfortunately ended up limiting the ability to scale it consistently.

**Comment by soundanalogous** [comment]
Will update Serial to 2.0 instead.

**Pull request closed without merging**
