### PR TITLE
single pin write

### PR DESCRIPTION
**Pull request by monteslu**

### CODE REVIEW

**Comment by soundanalogous** [comment]
Please add this to the [protocol.md file](https://github.com/firmata/protocol/blob/master/protocol.md) instead of creating a new file. Add a line in the table (just below the line for 0xF4) for the Message Types section and add the description to the Control Messages Expansion section.

**Comment by monteslu** [comment]
@soundanalogous  updated

**Comment by soundanalogous** [comment]
This looks good. Do you want to work on the implementation in firmata/arduino? If not I can probably get to it this weekend.

**Comment by monteslu** [comment]
I'm not that great of a C developer, but I can help test.  And I can work the client side implementations.

Figure if this gets a version bump, I can do the right thing with clients if the version matches.

**Pull request merged**
