### PR TITLE
Create ping.md

### PR DESCRIPTION
**Pull request by MrYsLab**
Initial proposal

### CODE REVIEW

**Comment by shostakun** [comment]
The original proposal was:
```
0  START_SYSEX
1  PING _DATA          (0x5E)
2  trigger pin
3  echo pin
4  max distance (lsb)
5  max distance (msb)
6  ping interval (time between sending a ping and retrieving the result)
7  END_SYSEX
```
Taking into account the new 3-byte [extended feature ID](https://github.com/firmata/protocol/blob/master/feature-registry.md#optional-feature-set) and the possibility of subcommands (e.g. start/stop) to be added in the future, this would become:
```
0  START_SYSEX
1  EXTENDED_ID
2  PING_DATA
3  PING_DATA
4  PING_ONCE
5  trigger pin
6  echo pin
7  max distance (lsb)
8  max distance (msb)
9  END_SYSEX
```
I'm not sure ping interval is needed.

The result would be:
```
0  START_SYSEX
1  EXTENDED_ID
2  PING_DATA
3  PING_DATA
4  trigger_pin
5  distance (LSB)
6  distance (MSB)
7  END_SYSEX
```

**Comment by soundanalogous** [comment]
Add a PING_REPLY command byte just before trigger_pin for the response.

Also if any configuration is necessary (configuring pins, etc) also add a CONFIG command.

**Comment by shostakun** [comment]
So for the reply:
```
0  START_SYSEX
1  EXTENDED_ID
2  PING_DATA
3  PING_DATA
4  PING_REPLY
5  trigger_pin
6  distance (LSB)
7  distance (MSB)
8  END_SYSEX
```
I don't see any need just yet for CONFIG. It can be added if necessary if someone wants to extend the protocol to include start/stop.

**Comment by shostakun** [comment]
After sleeping on it, I think it's much better to report the time of flight of the pulse rather than a converted distance:

1. It's consistent with existing implementations.
2. It's the least common denominator.
3. A standard (room temperature) conversion is trivial to do client-side and can be documented in the protocol and/or module documentation.
4. Some users may want to implement non-standard conversions for varying environmental conditions.

Using 16 bits for the time would allow a range of about 11 meters. But I suppose someday someone might want to build a long-range sensor, so maybe we should allow 32 bits to be on the safe side? 730 kilometers ought to be enough for everyone. Again, this is consistent with existing implementations.

So that is:
```
0  START_SYSEX
1  EXTENDED_ID
2  PING_DATA
3  PING_DATA
4  PING_REPLY
5  trigger_pin
6  time (LSB)
7  time
8  time
9  time (MSB)
10  END_SYSEX
```

**Comment by soundanalogous** [comment]
Use 32 bits like the `num steps` and `position` fields in the `Stepper step` and `Stepper to` commands of the [Stepper 2.0 proposal](https://github.com/firmata/protocol/blob/master/proposals/stepper-2.0.md).

**Comment by soundanalogous** [comment]
Actually were good just using 28 bits here so we can keep it as you have proposed above.

**Comment by shostakun** [comment]
Forgot about the 7-bit thing. 28 is plenty. I'll go ahead and write it up as an .md file. What should I use for the PING_DATA bytes?

**Comment by soundanalogous** [comment]
In thinking about whether or not we should use "PING_DATA" or "NEW_PING_DATA", I realized something I haven't thought about much before. The `PING_DATA` proposal (in its current state at least) is general enough that it could apply to any ping implementation. That means it would work for a NewPing library wrapper, but it could also work with another Ping library or even with the Arduino `pulseIn` function as long as the implementation conforms to the `PING_DATA` interface. This wouldn't work at all with the way features were traditionally implemented in StandardFirmata, but with the ConfigurableFirmata architecture since you'd only include one Ping implementation it makes sense that perhaps more than one could share the same protocol definition. The point where it breaks down is if a specific implementation requires a parameter that the user must supply, but I don't see that bing an issue with Ping, at least not yet.

I need to think more about this. If we can share an interface like this, I may be okay with using the 1 byte rather than 3 byte ID here.

**Comment by shostakun** [comment]
I'm actually planning on doing both in my implementation via preprocessor flags. For some cases where memory is tight, there are timer conflicts, or the chip doesn't support NewPing's timer functions, the traditional pulseIn implementation should be available.

I think we can also remove the max_distance bytes from the PING_READ command. This is an (optional) NewPing parameter, and it seems reasonable to `#define` it in the firmware. Same goes for the pulse_duration parameter used in [PingFirmata](https://gist.github.com/rwaldron/0519fcd5c48bfe43b827). If anyone actually wants to set these from the client, then maybe that's were the CONFIG subcommand comes in.

**Comment by soundanalogous** [comment]
How will you know if there are timer conflicts? For example say the user has 2 servos attached and a Ping sensor. I suspect there is a conflict between timers here on an ATMega328 or 32u4 since there are limited timers so Servos wouldn't work on certain pins if NewPing is used. It's a tricky issue to solve. Many users would not understand the reason for a conflict since they don't have a deep understanding of how microcontroller work and Firmata masks that complexity. Trying to check for such conditions in the preprocessor would get tedious as well.

**Comment by soundanalogous** [comment]
As long as there is little-to-no variation in the trigger pulse or max_distance among common ping-type sensors then I'm okay with using a #define for those values.

**Comment by soundanalogous** [comment]
Use this for the ID:

```
EXTENDED_ID       0x00
PING_DATA (LSB)   0x10
PING_DATA (MSB)   0x00
```

**Comment by shostakun** [comment]
No way I'd try to detect timer conflicts. The user would have to decide, and to me that's a documentation issue.

pulseIn should probably be the default as it's the most compatible. NewPing would be an option for users who want the performance gains, but the tradeoffs would have to be clearly outlined in the module docs. Fortunately, the NewPing and Arduino docs already do a good job of this. Trying to hide the complexity from the user seems like the worst choice, as they might naively enable NewPing and suddenly PWM stops working on certain pins with no explanation as to why...

From a user's standpoint, I don't see the difference between one module that provides two options or two modules. They still have to choose, so they would seem to be best served if the reasons why they should choose are clearly outlined.

**Comment by shostakun** [comment]
I'll write up a proposal using those values.

**Comment by soundanalogous** [comment]
How will a user understand if they are using NewPing or pulseIn under the hood?

**Comment by shostakun** [comment]
The user would have to uncomment a #define at compile time to enable NewPing.

**Comment by soundanalogous** [comment]
But the user would need to uncomment in NewPingFirmata.h right since Arduino precompiles any .c files when the Arduino IDE is launched. Or maybe this isn't an issue since it's a separate library. I forget what the exact build order is in that case.

**Comment by shostakun** [comment]
There's no mention of precompiling [here](https://www.arduino.cc/en/Hacking/BuildProcess). I'm new to the Arduino environment, but I was under the impression everything was compiled at the same time because I've got compiler warnings from libraries when compiling a sketch.

I just did some testing, though, and you're right that the #define has to go in the header file. I don't really see that as a problem, though.

These are implementation details anyway. Surely the first step is to get the protocol hammered out. Then I can tidy up and release my module(s). The last step is figuring out how exactly to do the ConfigurableFirmata integration.

**Comment by soundanalogous** [comment]
sounds good

**Comment by shostakun** [comment]
I have no clue about sensors other than the ones I'm using, so for config commands:

```
0  START_SYSEX
1  EXTENDED_ID        0x00
2  PING_DATA (LSB)    0x10
3  PING_DATA (MSB)    0x00
4  PING_CONFIG_PULSE_WIDTH
7  time_us (0-6)
8  time_us (7-13)
9  time_us (14-20)
10  time_us (21-27)
11  END_SYSEX
```

```
0  START_SYSEX
1  EXTENDED_ID        0x00
2  PING_DATA (LSB)    0x10
3  PING_DATA (MSB)    0x00
4  PING_CONFIG_MAX_DISTANCE
7  distance_cm (0-6)
8  distance_cm (7-13)
9  END_SYSEX
```

**Comment by soundanalogous** [comment]
Just took a look at the [NewPing documentation](https://bitbucket.org/teckel12/arduino-new-ping/wiki/Home) since it has been a while since I've reviewed the library. It looks like `MAX_DISTANCE` is passed to the constructor (but can optionally be passed each time the ping method is called). If also defaults to 500cm so if a sensor is capable of accurately reading a range greater than that, it's definitely useful to allow the user to specify `MAX_DISTANCE`. Since it is an optional constructor method, it may be better to define a single `PIN_CONFIG` message and include both time_us and distance_cm with that and mark them as optional. Since both are optional however we'd need to use a value of `0` to indicate that the default value should be used and then document this in the markdown file.

I assume `CONFIG_PUSLE_WIDTH` is only needed when using `pulseIn` since it's not a param that NewPing uses.

I also noticed that the NewPing constructor takes an optional separate echo pin. I'm not sure if there is a good use case for that or not. In most cases the same pin is used for both trigger and echo.

**Comment by soundanalogous** [comment]
Another thing to think about is if it makes sense for the user to use more than one ping sensor on a single board since some of the NewPing examples demonstrate using multiple sensors simultaneously. In that case we need to document a maximum number of instances and consider whether or not each instance should be configurable or if config spans all instances (so they all use the same pulse width and max_distance).

**Comment by shostakun** [comment]
TBH, supporting multiple sensors at the firmware level is just more complexity than I can undertake right now. I'd rather get basic support released first. You can handle multiple sensors from the client, anyway.

CONFIG_PUSLE_WIDTH is in keeping with PingFirmata, though it shouldn't be necessary for the user to specify it with a good default. NewPing lists one sensor that requires the second pin, and there's just no harm in including it.

**Comment by soundanalogous** [comment]
Okay lets keep CONFIG_PULSE_WIDTH out for now but keep MAX_DISTANCE and keep it optional. It may be useful to add trigger pin to the CONFIG message. That way if multiple pin sensors are supported in the future it won't require a non-backwards compatible change to do so.

**Pull request closed without merging**
